Repository JGCRI/gcamdata, pull requests merged in 2018-06, with the labels that each got.

#968 Split out compdata into its own package
  DESCRIPTION
  tests/testthat/test_oldnew.R
Labels: enhancement

#971 Change XML options
  R/driver.R
  R/onload.R
  R/utils.R
  man/driver.Rd
  man/save_chunkdata.Rd
Labels: enhancement

#973 OLDNEW-L2012.ag_For_Past
  R/zchunk_L2012.ag_For_Past_bio_input_irr_mgmt.R
Labels: oldnew

#981 Update CSVToXML.jar conversion utility for compatibility with Java 9/10
  inst/extdata/ModelInterface/CSVToXML.jar
Labels: bug

#987 OLDNEW aglu_batch_land_input_4_IRR_MGMT XML
  R/zchunk_batch_land_input_4_IRR_MGMT_xml.R
Labels: aglu, oldnew

#989 OLDNEW for L2233.electricity_water
  R/zchunk_L2233.electricity_water.R
Labels: oldnew

#997 Omnibus 988 990 991 992 993 996
  R/sysdata.rda
  R/zchunk_L2042.resbio_input_irr_mgmt.R
  R/zchunk_L210.resources.R
  R/zchunk_L2252.land_input_5_irr_mgmt.R
  R/zchunk_L241.fgas.R
  R/zchunk_L243.bio_trade_input.R
  R/zchunk_LA115.RooftopPV.R
  inst/extdata/temp-data-inject/L2252.LN5_MgdCarbon_bio_gcd5.csv
Labels: oldnew

#990 OLDNEW for L241.fgas
  R/zchunk_L241.fgas.R
Labels: oldnew

#991 OLDNEW for L243.bio_trade_input
  R/zchunk_L243.bio_trade_input.R
Labels: oldnew

#992 OLDNEW for L210.resources
  R/zchunk_L210.resources.R
Labels: oldnew

#993 OLDNEW for L2042.resbio_input_irr_mgmt
  R/zchunk_L2042.resbio_input_irr_mgmt.R
Labels: oldnew

#996 OLDNEW-LA115.RooftopPV
  R/zchunk_LA115.RooftopPV.R
Labels: oldnew

#994 OLDNEW - L110.water.demand.primary
  R/zchunk_L110.water.demand.primary.R
Labels: oldnew, water

#995 OLDNEW for L114.bcoc_en_R_S_T_Y
  R/zchunk_L114.bcoc_en_R_S_T_Y.R
Labels: oldnew

#1004 Omnibus 998 999 1001 1002 1003
  R/zchunk_L123.bcoc_awb_R_S_T_Y.R
  R/zchunk_L124.nonco2_unmgd_R_S_T_Y.R
  R/zchunk_LA119.solar-gcam-usa.R
  R/zchunk_LA154.Transport.R
  R/zchunk_LB134.Diet_Rfao.R
Labels: oldnew

#998 OLDNEW for LA119.Solar
  R/zchunk_LA119.solar-gcam-usa.R
Labels: oldnew

#999 OLDNEW for LB134.Diet_Rfao
  R/zchunk_LB134.Diet_Rfao.R
Labels: oldnew

#1001 OLDNEW for L123.bcoc_awb_R_S_T_Y
  R/zchunk_L123.bcoc_awb_R_S_T_Y.R
Labels: oldnew

#1002 OLDNEW for LA154.Transport
  R/zchunk_LA154.Transport.R
Labels: oldnew

#1003 OLDNEW-L124.nonco2_unmgd_R_S_T_Y
  R/zchunk_L124.nonco2_unmgd_R_S_T_Y.R
Labels: oldnew

#1009 Omnibus 1005 1006 1007 1008
  R/sysdata.rda
  R/zchunk_L112.ghg_en_R_S_T_Y.R
  R/zchunk_LA100.IMAGE_downscale_ctry_yr.R
  R/zchunk_LA107.an_IMAGE_R_C_Sys_Fd_Y.R
  R/zchunk_LA144.Commercial.R
  R/zchunk_LA144.Residential.R
  inst/extdata/temp-data-inject/L107.an_FeedIO_R_C_Sys_Fd_Y_gcd5.csv
Labels: oldnew

#1005 OLDNEW for L112.ghg_en_R_S_T_Y
  R/zchunk_L112.ghg_en_R_S_T_Y.R
Labels: oldnew

#1006 OLDNEW for LA144.Commercial;
  R/zchunk_LA144.Commercial.R
Labels: oldnew

#1007 OLDNEW for LA144.Residential
  R/zchunk_LA144.Residential.R
Labels: oldnew

#1014 Omnibus 1010 1011 1013
  R/zchunk_L100.Population_downscale_ctry.R
  R/zchunk_L102.ghg_en_USA_S_T_Y.R
  R/zchunk_L103.ghg_an_USA_S_T_Y.R
Labels: oldnew

#1010 OLDNEW for L102.ghg_en_USA_S_T_Y.R
  R/zchunk_L102.ghg_en_USA_S_T_Y.R
Labels: oldnew

#1011 OLDNEW for L103.ghg_an_USA_S_T_Y
  R/zchunk_L103.ghg_an_USA_S_T_Y.R
Labels: oldnew

#1013 OLDNEW for L100.Population_downscale_ctry
  R/zchunk_L100.Population_downscale_ctry.R
Labels: oldnew

#1020 Omnibus 1015 1017 1018
  R/sysdata.rda
  R/zchunk_L111.nonghg_en_R_S_T_Y.R
  R/zchunk_L270.limits.R
  R/zchunk_LA143.HDDCDD.R
  R/zchunk_batch_negative_emissions_budget_xml.R
  man/module_energy_L270.limits.Rd
  man/module_energy_batch_negative_emissions_budget_xml.Rd
Labels: oldnew

#1015 OLDNEW for L270.limits / Negative Emissions Budgets
  R/zchunk_L270.limits.R
  R/zchunk_batch_negative_emissions_budget_xml.R
  man/module_energy_L270.limits.Rd
  man/module_energy_batch_negative_emissions_budget_xml.Rd
Labels: oldnew

#1017 OLDNEW for LA143.HDDCDD
  R/zchunk_LA143.HDDCDD.R
Labels: oldnew

#1018 OLDNEW for L111.nonghg which had division of small numbers
  R/zchunk_L111.nonghg_en_R_S_T_Y.R
Labels: oldnew

#1021 Omnibus 1012 1016 1019
  R/constants.R
  R/module-helpers.R
  R/sysdata.rda
  R/zchunk_L161.nonghg_en_ssp_R_S_T_Y.R
  R/zchunk_L222.land_input_2.R
  R/zchunk_L2231.land_input_3_irr.R
  R/zchunk_LA114.wind-energy.R
  inst/extdata/energy/Zhou_wind_supply_ctry_EJ.csv
  inst/extdata/temp-data-inject/L114.OLDregional_price_supply_points.csv
Labels: oldnew
